#!/bin/bash 
# SETTINGS

export PATH=$HOME/bin:$PATH

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config split_ratio 0.5

# BORDERS + GAPS

bspc config border_width 3
bspc config window_gap   6

#bspc config border_width 0
#bspc config window_gap   0

bspc config presel_feedback_color \#EEEEEE
bspc config normal_border_color \#AAAAAA
bspc config focused_border_color \#FF99A1

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# RULES

bspc config external_rules_command "$(which rules)"

bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating

# UTILS

feh --bg-scale /usr/share/backgrounds/System76-Honeycomb-by_Kate_Hazen_of_System76.png
sxhkd &
compton &
polybar example &
#bar &

# vim: ft=sh
