#!/bin/bash 
# SETTINGS

export PATH=$HOME/bin:$PATH

#xset +fp ${HOME}/.fonts
#xset fp rehash

xsetroot -cursor_name left_ptr
xset 180 120

xrdb "${HOME}/.Xresources"

setxkbmap -option ctrl:nocaps

autorandr -c

# General settings

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config pointer_modifier mod1
bspc config pointer_action1 move


bspc config split_ratio 0.5

# BORDERS + GAPS

bspc config border_width 3
bspc config window_gap   6

#bspc config border_width 0
#bspc config window_gap   0

bspc config presel_feedback_color \#EEEEEE
bspc config normal_border_color \#AAAAAA
bspc config focused_border_color \#FF99A1

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# RULES

bspc config external_rules_command "$(which rules)"

bspc rule -a '*:floaty' state=floating

# UTILS

mkdir -p $HOME/logs

sxhkd_loop() {
    sxhkd 2>&1 >/dev/null | tee $HOME/logs/sxhkd-errors.txt | while read line; do
        notify-send.sh -u critical -r 3033 "$line"
    done
}

$HOME/.fehbg
xss-lock -- sxlock &
sxhkd_loop &
compton &
dunst &
battery-status-loop &

# vim: ft=sh
